version: "3"

services:
  app:
    build: ./
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./app:/nuxt_app
      - ~/.bashrc:/root/.bashrc:ro
      - ~/.bash_profile:/etc/profile:ro
    command: /bin/ash
    tty: true
